"""Add uuid colomn and delete operation_id column in Operations table

Revision ID: 4b5d7ce699fe
Revises: 283c27e1d397
Create Date: 2025-12-06 13:51:28.227487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5d7ce699fe'
down_revision: Union[str, Sequence[str], None] = '283c27e1d397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('uuid', sa.UUID(), nullable=False))
    op.drop_column('operations', 'operation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('operation_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('operations', 'uuid')
    # ### end Alembic commands ###
