"""Add unique constraint to inventory daily

Revision ID: 886264e452fe
Revises: 4b5d7ce699fe
Create Date: 2025-12-07 21:33:14.015278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886264e452fe'
down_revision: Union[str, Sequence[str], None] = '4b5d7ce699fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_room_type_id', 'inventory_daily', ['room_type_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_room_type_id', 'inventory_daily', type_='unique')
    # ### end Alembic commands ###
